[package]
name = "punchcard"
version = "0.1.0"
authors = ["Alexandre Bl√©ron <alex.bleron@gmail.com>"]

[dependencies]
bitflags = "*"
lazy_static = "*"
smallvec = "*"
pretty_env_logger = "*"
libc = "*"
log = "*"
winit = "*"
glutin = "*"
gl = "*"
failure = "*"
petgraph="*"
cassowary="*"
diff="*"
rand="*"
indexmap="*"
time="*"
num="*"

[dependencies.nanovg]
path = "../ext/nanovg-rs"
features = ["gl3"]

[dependencies.yoga]
path = "../ext/yoga-rs"
